site_name: CalTRACK Technical Documentation
theme: readthedocs
site_description: 'Technical Documentation for CalTRACK savings estimation'

extra_javascript:
    - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math

pages:
- Home: index.md
- Getting Started Guides:
  - Guide to Version 1.0 Monthly Methods: guides/v1guide.md
  - Guide to Version 1.1 Daily Methods: guides/v1.1guide.md
- Monthly:
  - Data Sources for Monthly Methods: monthly/data-sources.md
  - Data Preparation for Monthly Methods: monthly/data-prep.md
  - Analysis of Monthly Data: monthly/analysis.md
  - Aggregration of Site-level Savings: monthly/aggregation.md
