site_name: CalTRACK Technical Documentation
theme: readthedocs
docs_dir: docs
repo_url: https://github.com/caltrack-2/caltrack
site_url: http://docs.caltrack.org
site_description: 'Technical Documentation for CalTRACK savings estimation procedures'

extra_javascript:
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math

pages:
- Home: index.md
- Technical Specifications:
  - Data Sources: v1.0/data-sources/README.md
  - Data Preparation: v1.0/data-prep/README.md
  - Analysis of Monthly Data: v1.0/savings-calculations/monthly/README.md
  - Analysis of Daily Data: v1.0/savings-calculations/daily/README.md
  - Aggregration of Site-level Savings: v1.0/aggregation/README.md
- CalTRACKv2.0: v2.0/README.md
